"""add shift_template

Revision ID: 07594d4c7f22
Revises: 
Create Date: 2025-09-07 23:03:06.622167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07594d4c7f22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('role_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift_template')
    # ### end Alembic commands ###
